sudo: false
dist: trusty
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy: heroku
  app: boiling-cove-38380
  api_key:
    secure: rIhm+0YZkESDLe9VsHlEaT5c6Qq8F9Ha4q6lcUwu1DUSIKaAOpSZvXZI9ZUyetbw1She3gdkmTGhzs2bwJCsmnu9bz7LgENNAYBuW0vylwztnvt8hOW6CMkFIIaFfV4PdoAJojYMtgzj629LnvcvYDkSJ8ZMxIUXDcNYa9Sgtq/zbrtHU2efw3k1xAg4ODLI1cnhzHHxloelQr8clkaHr91Bga1ixUUmlkLbSySzS/PVFVxfBkGtmeUpMbLkfl4NMykJX9oUiCkX3TUi5dL4kaPVuTf7RwqHIVgO94cB1MKX/siWM6RczLvRPJSPYp9p7Sq6/2ktuumxNiFMiK3BBMbaM3XUrXIGiq3FVo3TNJTWBnLwpcd2TS4ZDugHD6rqUIqbFBHp30BGwo9IKFN633KkC8fqa98qMjvLkRGto/xDqlfd0quMiZPIXA7OyHwJ1DC9yCwqacy6Hg2EMoEwEKGAWE89nE7LnJPQOUl22Pd5fj/T/pA4O1GDofKi+Yv9FOq6AhJ3DQXeErHLd/WnfyZG2h1l7nGa2J7wbm2cgKEEETZLOrKfw6mlt/6YW0gWvALZtalnXtW+hRzuI1I8pqeuxTvdkARoSMHZWN6zAuWPzmpOvV+GJycjb29JR7JQXcnP8s0IXY2yifNqBk0Bl4Ani027TYdTxFg65Ic1VPw=
